// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: api/location.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vin           string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LocationRequest) Reset() {
	*x = LocationRequest{}
	mi := &file_api_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LocationRequest) ProtoMessage() {}

func (x *LocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LocationRequest.ProtoReflect.Descriptor instead.
func (*LocationRequest) Descriptor() ([]byte, []int) {
	return file_api_location_proto_rawDescGZIP(), []int{0}
}

func (x *LocationRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *LocationRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *LocationRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *LocationRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_api_location_proto protoreflect.FileDescriptor

const file_api_location_proto_rawDesc = "" +
	"\n" +
	"\x12api/location.proto\x12\blocation\"e\n" +
	"\x0fLocationRequest\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestampB9Z7github.com/jojohimawan/intelligent-agent-system/api;apib\x06proto3"

var (
	file_api_location_proto_rawDescOnce sync.Once
	file_api_location_proto_rawDescData []byte
)

func file_api_location_proto_rawDescGZIP() []byte {
	file_api_location_proto_rawDescOnce.Do(func() {
		file_api_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_location_proto_rawDesc), len(file_api_location_proto_rawDesc)))
	})
	return file_api_location_proto_rawDescData
}

var file_api_location_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_location_proto_goTypes = []any{
	(*LocationRequest)(nil), // 0: location.LocationRequest
}
var file_api_location_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_location_proto_init() }
func file_api_location_proto_init() {
	if File_api_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_location_proto_rawDesc), len(file_api_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_location_proto_goTypes,
		DependencyIndexes: file_api_location_proto_depIdxs,
		MessageInfos:      file_api_location_proto_msgTypes,
	}.Build()
	File_api_location_proto = out.File
	file_api_location_proto_goTypes = nil
	file_api_location_proto_depIdxs = nil
}
