// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.6
// source: api/telematics.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TelematicsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vin           string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	CaptureTime   *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=capture_time,json=captureTime,proto3" json:"capture_time,omitempty"`
	Signals       []*Telematics          `protobuf:"bytes,3,rep,name=signals,proto3" json:"signals,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TelematicsBatch) Reset() {
	*x = TelematicsBatch{}
	mi := &file_api_telematics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TelematicsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TelematicsBatch) ProtoMessage() {}

func (x *TelematicsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_telematics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TelematicsBatch.ProtoReflect.Descriptor instead.
func (*TelematicsBatch) Descriptor() ([]byte, []int) {
	return file_api_telematics_proto_rawDescGZIP(), []int{0}
}

func (x *TelematicsBatch) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *TelematicsBatch) GetCaptureTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CaptureTime
	}
	return nil
}

func (x *TelematicsBatch) GetSignals() []*Telematics {
	if x != nil {
		return x.Signals
	}
	return nil
}

type Telematics struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Source string                 `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Param  string                 `protobuf:"bytes,2,opt,name=param,proto3" json:"param,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Telematics_DoubleVal
	//	*Telematics_IntVal
	//	*Telematics_BoolVal
	//	*Telematics_StringVal
	Value         isTelematics_Value `protobuf_oneof:"value"`
	Unit          string             `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Telematics) Reset() {
	*x = Telematics{}
	mi := &file_api_telematics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Telematics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Telematics) ProtoMessage() {}

func (x *Telematics) ProtoReflect() protoreflect.Message {
	mi := &file_api_telematics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Telematics.ProtoReflect.Descriptor instead.
func (*Telematics) Descriptor() ([]byte, []int) {
	return file_api_telematics_proto_rawDescGZIP(), []int{1}
}

func (x *Telematics) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Telematics) GetParam() string {
	if x != nil {
		return x.Param
	}
	return ""
}

func (x *Telematics) GetValue() isTelematics_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Telematics) GetDoubleVal() float64 {
	if x != nil {
		if x, ok := x.Value.(*Telematics_DoubleVal); ok {
			return x.DoubleVal
		}
	}
	return 0
}

func (x *Telematics) GetIntVal() int64 {
	if x != nil {
		if x, ok := x.Value.(*Telematics_IntVal); ok {
			return x.IntVal
		}
	}
	return 0
}

func (x *Telematics) GetBoolVal() bool {
	if x != nil {
		if x, ok := x.Value.(*Telematics_BoolVal); ok {
			return x.BoolVal
		}
	}
	return false
}

func (x *Telematics) GetStringVal() string {
	if x != nil {
		if x, ok := x.Value.(*Telematics_StringVal); ok {
			return x.StringVal
		}
	}
	return ""
}

func (x *Telematics) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

type isTelematics_Value interface {
	isTelematics_Value()
}

type Telematics_DoubleVal struct {
	DoubleVal float64 `protobuf:"fixed64,3,opt,name=double_val,json=doubleVal,proto3,oneof"`
}

type Telematics_IntVal struct {
	IntVal int64 `protobuf:"varint,4,opt,name=int_val,json=intVal,proto3,oneof"`
}

type Telematics_BoolVal struct {
	BoolVal bool `protobuf:"varint,5,opt,name=bool_val,json=boolVal,proto3,oneof"`
}

type Telematics_StringVal struct {
	StringVal string `protobuf:"bytes,6,opt,name=string_val,json=stringVal,proto3,oneof"`
}

func (*Telematics_DoubleVal) isTelematics_Value() {}

func (*Telematics_IntVal) isTelematics_Value() {}

func (*Telematics_BoolVal) isTelematics_Value() {}

func (*Telematics_StringVal) isTelematics_Value() {}

var File_api_telematics_proto protoreflect.FileDescriptor

const file_api_telematics_proto_rawDesc = "" +
	"\n" +
	"\x14api/telematics.proto\x12\n" +
	"telematics\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x01\n" +
	"\x0fTelematicsBatch\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12=\n" +
	"\fcapture_time\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\vcaptureTime\x120\n" +
	"\asignals\x18\x03 \x03(\v2\x16.telematics.TelematicsR\asignals\"\xd1\x01\n" +
	"\n" +
	"Telematics\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x12\x14\n" +
	"\x05param\x18\x02 \x01(\tR\x05param\x12\x1f\n" +
	"\n" +
	"double_val\x18\x03 \x01(\x01H\x00R\tdoubleVal\x12\x19\n" +
	"\aint_val\x18\x04 \x01(\x03H\x00R\x06intVal\x12\x1b\n" +
	"\bbool_val\x18\x05 \x01(\bH\x00R\aboolVal\x12\x1f\n" +
	"\n" +
	"string_val\x18\x06 \x01(\tH\x00R\tstringVal\x12\x12\n" +
	"\x04unit\x18\a \x01(\tR\x04unitB\a\n" +
	"\x05valueB9Z7github.com/jojohimawan/intelligent-agent-system/api;apib\x06proto3"

var (
	file_api_telematics_proto_rawDescOnce sync.Once
	file_api_telematics_proto_rawDescData []byte
)

func file_api_telematics_proto_rawDescGZIP() []byte {
	file_api_telematics_proto_rawDescOnce.Do(func() {
		file_api_telematics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_telematics_proto_rawDesc), len(file_api_telematics_proto_rawDesc)))
	})
	return file_api_telematics_proto_rawDescData
}

var file_api_telematics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_telematics_proto_goTypes = []any{
	(*TelematicsBatch)(nil),       // 0: telematics.TelematicsBatch
	(*Telematics)(nil),            // 1: telematics.Telematics
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_telematics_proto_depIdxs = []int32{
	2, // 0: telematics.TelematicsBatch.capture_time:type_name -> google.protobuf.Timestamp
	1, // 1: telematics.TelematicsBatch.signals:type_name -> telematics.Telematics
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_telematics_proto_init() }
func file_api_telematics_proto_init() {
	if File_api_telematics_proto != nil {
		return
	}
	file_api_telematics_proto_msgTypes[1].OneofWrappers = []any{
		(*Telematics_DoubleVal)(nil),
		(*Telematics_IntVal)(nil),
		(*Telematics_BoolVal)(nil),
		(*Telematics_StringVal)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_telematics_proto_rawDesc), len(file_api_telematics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_telematics_proto_goTypes,
		DependencyIndexes: file_api_telematics_proto_depIdxs,
		MessageInfos:      file_api_telematics_proto_msgTypes,
	}.Build()
	File_api_telematics_proto = out.File
	file_api_telematics_proto_goTypes = nil
	file_api_telematics_proto_depIdxs = nil
}
